### ISSUE TITLE
TypeError: Cannot read property 'params' of undefined

### ISSUE THREAD

**Issue by Goobaroo** [chibidev/homebridge-unraid#34]
Seems like it can't read the config, I only have 1 server not two.  It is a bit unclear from the example what the IPs are, if just the unRaid server or the VMs themselves.

### Error
> [10/29/2020, 8:19:08 PM] [Unraid] Initializing UnraidServerPlatform platform...
[10/29/2020, 8:19:08 PM] [Unraid] Your config is outdated. It will be temporarily converted to the latest format, but you should consider updating your config file.
[10/29/2020, 8:19:08 PM] TypeError: Cannot read property 'params' of undefined
    at /usr/local/lib/node_modules/homebridge-unraid/dist/server/models/config.js:90:41
    at Array.map (<anonymous>)
    at migrate (/usr/local/lib/node_modules/homebridge-unraid/dist/server/models/config.js:86:46)
    at /usr/local/lib/node_modules/homebridge-unraid/dist/util/functional.js:5:69
    at Array.reduceRight (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-unraid/dist/util/functional.js:5:20
    at /usr/local/lib/node_modules/homebridge-unraid/dist/lib/config.js:13:25
    at Object.initialize (/usr/local/lib/node_modules/homebridge-unraid/dist/lib/config.js:21:38)
    at new Platform (/usr/local/lib/node_modules/homebridge-unraid/dist/lib/platform.js:65:42)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:397:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

### Config
>{
        "platform": "UnraidServerPlatform",
        "name": "Unraid",
        "machines": [
          {
            "id": "lucifer",
            "enableContainers": false,
            "enableVMs": true,
            "host": {
              "monitor": {
                "type": "ssh+poll",
                "interval": 15,
                "ip": "root@192.168.0.66"
              },
              "publish": true,
              "ip": "192.168.0.66",
              "switchOffMechanism": "shutdown"
            }
          }
        ],
        "updateInterval": 5
      }

**Comment by Goobaroo** [comment]
Actually, it looks like it is having an issue updating the config, maybe the docs are out of date?

**Comment by chibidev** [comment]
Not really out-of-date, but there's definitely an issue. I left "updateInterval" in the example by mistake (it was required by a previous version), that's why homebridge-unraid mistakes your config to be an older version and tries to upgrade it (and fail). Remove the "updateInterval" property from the json and I think you'll be good to go.

I'll fix the doc next week.

**Comment by Goobaroo** [comment]
Thanks, it's working now.
